# Generated by Django 5.1 on 2024-08-27 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategory',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('icon', models.ImageField(upload_to='kategory_icons')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, default='example-dish.jpg', null=True, upload_to='dish_images')),
                ('description', models.TextField()),
                ('calories', models.FloatField(blank=True, default=0, null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('persons', models.IntegerField(blank=True, default=1, null=True)),
                ('is_public', models.BooleanField(blank=True, default=False, null=True)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=502)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=502)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipesection')),
            ],
        ),
    ]
