# Generated by Django 5.1 on 2024-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipesectionentry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='kategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='kategory_icons'),
        ),
    ]
