# Generated by Django 5.1 on 2024-08-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dish_img_alter_kategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images'),
        ),
    ]
